### ISSUE TITLE
client auto-disconnect itself

### ISSUE THREAD

**Issue by leopaoca** [Maxi35/pyrelay#29]
My bots are auto disconnecting from servers with these errors:

`Client forcefully disconnected from 3.140.254.133
Exception in thread Thread-157564:
Traceback (most recent call last):
  File "/home/rpzleopaoca13/pyrelay/Networking/SocketManager.py", line 98, in _listen
    recv = self.sock.recv(HEADERSIZE)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rpzleopaoca13/pyrelay/Networking/SocketManager.py", line 104, in _listen
    self.disconnect(False)
  File "/home/rpzleopaoca13/pyrelay/Networking/SocketManager.py", line 86, in disconnect
    self.sock.shutdown(socket.SHUT_RDWR)
OSError: [Errno 107] Transport endpoint is not connected`

**Comment by Maxi35** [comment]
Was the server you tried to connect to full?

**Comment by leopaoca** [comment]
Nope.
The servers that I tried are all avaliable, not even crowded

**Comment by leopaoca** [comment]
At the start it connects, and works perfectly. But after like, 1 minute it throws this error.
I'm using socks5 proxies from webshare btw

If you use proxies, recommend me a good one

**Comment by Maxi35** [comment]
Yea seems like it is just a proxy issue then, I don't use proxies so sry can't recommend one
