### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by DrCrally** [Maxi35/pyrelay#6]
Trace:

Exception in thread Thread-37101:
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\****\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\****\Desktop\pyrelay-master\Networking\SocketManager.py", line 121, in _listen
    packet.read(self.reader)
  File "C:\Users\****\Desktop\pyrelay-master\Networking\Packets\Incoming\DamagePacket.py", line 21, in read
    self.objectId = reader.readInt32()
  File "C:\Users\****\Desktop\pyrelay-master\Networking\Reader.py", line 20, in readInt32
    value = struct.unpack("!i", self.buffer[self.index:self.index+4])[0]
struct.error: unpack requires a buffer of 4 bytes

Seems to happen anywhere from a few seconds after the bot starts to a few minutes but it does always occur eventually.
No idea what's causing it.

**Comment by DrCrally** [comment]
For now I've commented out the offending line in DamagePacket.py:
`self.objectId = reader.readInt32()`
This seems to have fixed the error me for me

**Comment by Maxi35** [comment]
Should be fixed in latest commit [dc468d8](https://github.com/Maxi35/pyrelay/commit/dc468d8612226325b07dafcdd97cb831b2c7f453)
